### ISSUE TITLE
Consider switching to https://github.com/mwiede/jsch

### ISSUE THREAD

**Issue by mikehearn** [robtimus/sftp-fs#11]
Original jsch isn't that well maintained. @mwiede has forked it and is maintaining it better. It'd be nice to use it by default.

**Comment by robtimus** [comment]
To be honest, I was a bit hesitant to switch to just any library. However, [camel-jsch](https://mvnrepository.com/artifact/org.apache.camel/camel-jsch) uses it, so if the Apache Camel team trusts it, I guess I can too.

I have been trying to upgrade, but it's not as much of a drop-in as @mwiede promises. Apart from a few small code changes, I have a lot of failing unit tests. That may be partly because I'm using an older `sshd-core` version, so I'll have to see if upgrading that will solve things. Unfortunately, it's a major version change so that will require some effort.

**Comment by robtimus** [comment]
FYI, I have finalized the switch to this new implementation on a branch. I want to finalize that soon, together with #10.

**Comment by robtimus** [comment]
Part of version 3.0, which has just been released.

**Comment by mikehearn** [comment]
Thanks!!
