### ISSUE TITLE
java.nio.file.FileSystemAlreadyExistsException

### ISSUE THREAD

**Issue by dstroyrofworlds** [robtimus/sftp-fs#5]
When create a new filesystem why can I not create 2 to the same host and username?

I have a batch program that will open and close the connections.
If I have 2 processes running and one closes it I'll get an exception.
If 1 is already running and another tries to open a filesystem I get the java.nio.file.FileSystemAlreadyExistsException: exception.

The logic does not make sense for me.

**Comment by robtimus** [comment]
The reason for this is mostly the `getFileSystem` method of `FileSystemProvider`. Given a URI, this should return the matching file system. If `newFileSystem` would allow duplicates, then `getFileSystem` could not return a single file system that would be the correct one in all cases.

There is a way around this though. The file systems are stored per instance of `SFTPFileSystemProvider`. That means that you can still get two file systems to the same host with the same username. All you need to do is stop using `FileSystems.newFileSystem`, since this uses a single cached `SFTPFileSystemProvider`. Instead, use an `SFTPFileSystemProvider` per process. For instance:

    FileSystem fs = new SFTPFileSystemProvider().newFileSystem(URI.create("sftp://example.org"), env));

**Comment by dstroyrofworlds** [comment]
A most excellent solution. Thanks.

**Comment by robtimus** [comment]
You're welcome.
